apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cleanup-jobs-binding
  namespace: cleanup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cleanup-jobs-role
subjects:
- kind: ServiceAccount
  name: cleanup-jobs-sa
  namespace: cleanup